### ISSUE TITLE
ScenceView Show model in the front of other view

### ISSUE THREAD

**Issue by Amitdygon** [sceneview/sceneview#52]
I am using Scence view to show 3D model in a view but its show on the top of all view Here i add my code and file
![Screenshot_20220324_124156](https://user-images.githubusercontent.com/45029280/159862661-edb89740-a52c-4377-9708-4f66bbb273ca.png)
[Screenshot_20220324_124156.zip](https://github.com/SceneView/sceneview-android/files/8339215/Screenshot_20220324_124156.zip)

https://user-images.githubusercontent.com/45029280/159862687-02da138f-3034-4531-911a-d12a11beb669.mp4

**Comment by ThomasGorisse** [comment]
Nice work!
In your case, you have to change the background of the `SceneView` to a non transparent one or use an HDR or KTX environment.
Transparency in case of `SurfaceView` has a clear color so it cannot handle your behind view redraw to make them appear on the foreground.

**Comment by ThomasGorisse** [comment]
How did you handle the gestures since we didn't introduced it yet?

**Comment by Amitdygon** [comment]
Here I attach my Code you can check it 
[ProfileFragment.zip](https://github.com/SceneView/sceneview-android/files/8339493/ProfileFragment.zip)
.

**Comment by ninjz** [comment]
> Here I attach my Code you can check it
> [ProfileFragment.zip](https://github.com/SceneView/sceneview-android/files/8339493/ProfileFragment.zip)
> .

Looks like this is using sceneform instead of sceneview. I have to say the naming of the two packages now is quite confusing as I had to really squint to see that you were referring to a new library called sceneview when I was going through issues inside of the sceneform project @ThomasGorisse
